// <auto-generated />
using System;
using Jegyek.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jegyek.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Jegyek.Models.User", b =>
                {
                    b.Property<Guid>("Azon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Jegy")
                        .HasColumnType("int");

                    b.Property<string>("Leiras")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ido")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Azon");

                    b.ToTable("Tantargy");
                });
#pragma warning restore 612, 618
        }
    }
}
